#DB Connection
server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto : update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_com_db
    username: root
    password: password

#server.port = 8081
##spring.config.activate.on-profile = local
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url = jdbc:mysql://localhost:3306/e_com_db
#spring.datasource.username=root
#spring.datasource.password=password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true